### ISSUE TITLE
RPC Error: Internal JSON-RPC error - VM Exception while processing transaction

### ISSUE THREAD

**Issue by yao23** [dappuniversity/dbank#4]
I tried Payoff feature but facing following error, any suggestion to fix?

My code - https://github.com/yao23/Blockchain_Playground

Chrome - Version 90.0.4430.212 (Official Build) (x86_64)

Error message:

```
MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: "Internal JSON-RPC error.", data: {…}}
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
async function (async)
_processRequest @ inpage.js:17
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
sendAsync @ inpage.js:1
push../node_modules/web3-core-requestmanager/src/index.js.RequestManager.send @ index.js:132
sendRequest @ index.js:705
send @ index.js:726
_executeMethod @ index.js:920
_callee6$ @ App.js:90
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
payOff @ App.js:91
onClick @ App.js:225
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:414
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 15 more frames
App.js:101 Error, pay off:  Error: Internal JSON-RPC error.
{
  "message": "VM Exception while processing transaction: revert",
  "code": -32000,
  "data": {
    "0xa10ec14ba1fc668ddf06bdd9267d86c4c2426933d4613b9b7d76f5471e28758c": {
      "error": "revert",
      "program_counter": 117,
      "return": "0x"
    },
    "stack": "RuntimeError: VM Exception while processing transaction: revert\n    at Function.RuntimeError.fromResults (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:568:26",
    "name": "RuntimeError"
  }
}
    at Object._fireError (index.js:57)
    at sendTxCallback (index.js:614)
    at index.js:136
    at s._handle (inpage.js:17)
```

```
index.js:57 Uncaught (in promise) Error: Internal JSON-RPC error.
{
  "message": "VM Exception while processing transaction: revert",
  "code": -32000,
  "data": {
    "0xa10ec14ba1fc668ddf06bdd9267d86c4c2426933d4613b9b7d76f5471e28758c": {
      "error": "revert",
      "program_counter": 117,
      "return": "0x"
    },
    "stack": "RuntimeError: VM Exception while processing transaction: revert\n    at Function.RuntimeError.fromResults (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:568:26",
    "name": "RuntimeError"
  }
}
    at Object._fireError (index.js:57)
    at sendTxCallback (index.js:614)
    at index.js:136
    at s._handle (inpage.js:17)
```
<img width="1437" alt="Screen Shot 2021-05-22 at 1 56 14 PM" src="https://user-images.githubusercontent.com/3107449/119240597-8bd2a300-bb05-11eb-9bee-8a47d23f467b.png">

**Comment by ashalfarhan** [comment]
Ya, i'm facing the same issue after trying to deposit for the second time after the first one.

**Comment by athenayay** [comment]
Enter TX has here to decode 
https://www.moesif.com/solidity-abi-hex-decoder/decode?radioGroup=on

A
