### ISSUE TITLE
Error when compile: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by kuchaguangjie** [dappuniversity/dbank#7]
Get following error when compile, any idea ?

```
$ truffle migrate

Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
Error: TypeError: Cannot convert undefined or null to object
    at VersionRange.load (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js:207:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CompilerSupplier.load (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/index.js:71:1)
    at loadParser (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/loadParser.js:15:29)
    at Object.requiredSources (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/index.js:19:1)
    at Object.sourcesWithDependencies (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:125:45)
    at necessary (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:92:1)
    at /home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:35:1
    at async Promise.all (index 0)
    at compile (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:25:1)
    at Object.compile (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:68:47)
    at Object.compileAndSave (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:95:47)
    at Object.run (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:199:1)
    at Command.run (/home/eric/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:172:1)
Truffle v5.4.5 (core: 5.4.5)
Node v14.17.0
```

**Comment by aqeelahcodes** [comment]
The solution is to check your code and fix the null/undefined condition so that the function either gets a proper Object, or does not get called at all.
